"""What every tool result looks like, and the limits it is held to.

Docs: https://vedicreader.github.io/shalya/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['MAX_TOOL_CHARS', 'MAX_HITS', 'MAX_GREP_HITS', 'MAX_API', 'MAX_FILE', 'ERR', 'SANDBOX', 'SECRET', 'NO_ROOTS', 'DENY',
           'GIT_READ_TOOLS', 'GIT_WRITE_TOOLS', 'GIT_TOOLS', 'WRITE_TOOLS', 'Hit', 'HostError', 'host_err', 'err',
           'failed', 'Unsafe', 'denied', 'Sandbox', 'clip', 'clip_lines', 'cmds', 'edits', 'apply_edits', 'diff_text',
           'writes', 'is_write']

# %% ../nbs/00_core.ipynb #8ff4e050
import json, os
from fastcore.basics import AttrDict, first, listify
from fastcore.foundation import L
from fastcore.xtras import Path, str_diff

# %% ../nbs/00_core.ipynb #9af4b779
MAX_TOOL_CHARS = 6000   # chars per tool result, budgeted for the smallest model
MAX_HITS = 20           # search hits one result carries
MAX_GREP_HITS = 60      # exact matches one `grep` returns. Part of the host contract
MAX_API = 200           # public names one `public_api` listing returns. Part of the same contract
MAX_FILE = 2_000_000    # bytes. A file larger than this is data, not source

# %% ../nbs/00_core.ipynb #53ab854f
class Hit(AttrDict):
    "One search hit: path, line, symbol, text."
    def __init__(self, path, line=1, symbol='', text=''): super().__init__(path=path, line=line, symbol=symbol, text=text)
    def __repr__(self): return f'{self.path}:{self.line}  {self.symbol}  {self.text}'

# %% ../nbs/00_core.ipynb #c55d1ed2
ERR = 'ERROR: '

class HostError(Exception): "A host refusal."

def host_err(e):
    "A caught exception, for a user-facing surface."
    return f'{type(e).__name__}: {e}'

def err(what, e=None):
    "One tool failure, spelled the way every other tool spells it."
    return f'{ERR}{what}' + (f': {host_err(e)}' if e is not None else '')

def failed(result):
    "Whether a tool result starts with `ERROR: `."
    return str(result or '').startswith(ERR)

# %% ../nbs/00_core.ipynb #a0da82f5
SANDBOX = 'path is outside the open folders'
SECRET = 'path holds credentials and is never read'
NO_ROOTS = 'no folders are open, so no path is inside them'

#: Credential-shaped paths refused even with `read_outside`. `fnmatch` on the resolved path.
DENY = ('*/.ssh/*', '*/.aws/*', '*/.gnupg/*', '*/.config/gcloud/*', '*/.netrc',
        '*/.git-credentials', '*/.codex/auth.json', '*/.claude/.credentials.json',
        '*/.env', '*/.env.*', '*/id_rsa*', '*/id_ed25519*', '*.pem', '*.key', '*.p12')

class Unsafe(HostError): "A path that resolves outside every open root, or one refused for safety."

def denied(path, patterns=DENY):
    "Whether `path` matches a refused credential path."
    from fnmatch import fnmatch
    s = Path(path).as_posix()
    return any(fnmatch(s, pat) for pat in patterns)

# %% ../nbs/00_core.ipynb #30649626
class Sandbox:
    "The open folders, and the one place that decides whether a path is inside them."
    def __init__(self,
                 roots=(),             # folders to open; each must already exist
                 read_outside=False,   # let reads name any path on this machine
                 deny=DENY):           # what `read_outside` still refuses to open
        self.roots, self.read_outside, self.deny = L(), bool(read_outside), tuple(deny or ())
        for r in roots: self.add_root(r)
    def __repr__(self): return f'Sandbox({[str(r) for r in self.roots]})'
    def covers(self, p):
        "Whether `p` is inside an open root, or is one of them."
        return any(Path(p).is_relative_to(r) for r in self.roots)
    def add_root(self, p):
        "Open a folder and close any open root inside it. Returns the root that now covers it."
        p = Path(p).expanduser().resolve()
        if not p.exists(): raise Unsafe(f'no such folder: {p}')
        if not p.is_dir(): raise Unsafe(f'not a folder, so it cannot be a root: {p}')
        if self.covers(p): return self.root_of(p)
        self.roots = L([r for r in self.roots if p not in r.parents]) + [p]
        return p
    def drop_root(self, p):
        "Close a folder. Nothing under it resolves any more."
        p = Path(p).expanduser().resolve()
        self.roots = self.roots.filter(lambda r: r != p)
        return p
    def check(self, path, must_exist=False, reading=False):
        "Resolve `path`, and refuse it unless it lands inside an open root."
        if not self.roots: raise Unsafe(f'{NO_ROOTS}: {path}')
        p = Path(path).expanduser()
        if not p.is_absolute(): p = self.roots[0]/p
        p = p.resolve()
        if not self.covers(p):
            if not (reading and self.read_outside): raise Unsafe(f'{SANDBOX}: {p}')
            if denied(p, self.deny): raise Unsafe(f'{SECRET}: {p}')
        if must_exist and not p.exists(): raise Unsafe(f'no such file: {p}')
        return p
    def root_of(self, path):
        "The open root holding `path`, or None when `read_outside` let it through from elsewhere."
        p = self.check(path, reading=True)
        return first(r for r in self.roots if p.is_relative_to(r))
    def bare(self, name):
        "A name typed by a person or a model, refused unless it is one path component."
        if '/' in name or os.sep in name or name in ('', '.', '..'): raise Unsafe(f'{name!r} is not a bare filename')
        return name
    def under(self, path, name):
        "Where an entry called `name` goes inside `path`. `name` is one component, never a path."
        return self.check(self.check(path)/self.bare(name))

# %% ../nbs/00_core.ipynb #a2c88077
def clip(s, n=MAX_TOOL_CHARS, more=''):
    "Truncate a tool result to `n` chars. A caller with a way to resume passes it as `more`."
    s = str(s)
    if len(s) <= n: return s
    cut = s[:n]
    nl = cut.rfind('\n')
    if nl > n * 0.6: cut = cut[:nl]
    note = f'[truncated: {len(cut)} of {len(s)} chars shown'
    return cut + f'…{note}. {more}]' if more else cut + f'…{note}]'

# %% ../nbs/00_core.ipynb #7ca20dbc
def clip_lines(lines, start=1, n=MAX_TOOL_CHARS, more='', empty='(nothing)'):
    "Render `lines` within the budget, and say which line to resume from."
    lines = listify(lines)
    if not lines: return empty
    out, used = [], 0
    for i, line in enumerate(lines):
        line = str(line)
        if used + len(line) + 1 > n:
            if out:
                rest = len(lines) - i
                tail = f'\n…[{rest} more line(s) not shown'
                hint = more.format(next=start + i) if '{next}' in more else more
                return '\n'.join(out) + (f'{tail}. {hint}]' if hint else f'{tail}]')
            keep, rest = max(1, n - 1), len(lines) - 1
            more_lines = f', and {rest} more line(s) not shown' if rest else ''
            return line[:keep] + f'\n…[line {start} is {len(line)} chars; {keep} shown{more_lines}]'
        out.append(line); used += len(line) + 1
    return '\n'.join(out)

# %% ../nbs/00_core.ipynb #d67ed39a
def cmds(commands):
    "Models emit JSON and exhash wants tuples, nested ones included: `[[...]]` becomes `[(...)]`."
    if isinstance(commands, str): commands = json.loads(commands)
    if not isinstance(commands, list): raise ValueError('commands must be a JSON list of command arrays')
    def _t(c):
        if not isinstance(c, (list, tuple)): raise ValueError(f'each command must be an array, got {type(c).__name__}')
        return tuple(_t(x) if isinstance(x, (list, tuple)) else x for x in c)
    return [_t(c) for c in commands]

# %% ../nbs/00_core.ipynb #c75c5591
def edits(es):
    "A JSON string, `{'oldText','newText'}` dicts, or `[old, new]` pairs: all three are unambiguous."
    if isinstance(es, str): es = json.loads(es)
    if isinstance(es, dict): es = [es]
    if not isinstance(es, (list, tuple)): raise ValueError('edits must be a JSON array')
    out = []
    for e in es:
        if isinstance(e, dict):
            if 'oldText' not in e or 'newText' not in e: raise ValueError("each edit needs 'oldText' and 'newText'")
            out.append((str(e['oldText']), str(e['newText'])))
        elif isinstance(e, (list, tuple)) and len(e) == 2: out.append((str(e[0]), str(e[1])))
        else: raise ValueError('each edit must be {"oldText":…,"newText":…} or [old, new]')
    return out

def apply_edits(text, es):
    "Apply exact-text edits to `text`, or raise saying which one is wrong and why."
    spans = []
    for i, (old, new) in enumerate(es, 1):
        if not old: raise ValueError(f'edit {i}: oldText is empty; use create_file to write a whole file')
        n = text.count(old)
        if n == 0: raise ValueError(f'edit {i}: oldText not found. It must match the file exactly, including indentation. Re-read the file and try again')
        if n > 1: raise ValueError(f'edit {i}: oldText matches {n} places. Include more surrounding lines so it matches exactly one')
        at = text.index(old)
        spans.append((at, at + len(old), new, i))
    spans.sort()
    for (s1, e1, _, i1), (s2, _, _, i2) in zip(spans, spans[1:]):
        if s2 < e1: raise ValueError(f'edits {i1} and {i2} overlap; merge them into one edit')
    out, at = [], 0
    for s, e, new, _ in spans:
        out.append(text[at:s])
        out.append(new)
        at = e
    out.append(text[at:])
    return ''.join(out)

# %% ../nbs/00_core.ipynb #c6041489
def diff_text(before, after, path='file'):
    "Return a unified diff."
    return str_diff(before, after, n=2, names=(f'a/{path}', f'b/{path}'))

# %% ../nbs/00_core.ipynb #399d9f51
def writes(f):
    "Mark a tool as one that changes something. `Approvals` puts these in front of a person."
    f.writes = True
    return f

def is_write(t):
    "Whether `t` is a tool that changes something."
    return bool(getattr(t, 'writes', False))

#: Rehearsing a merge is not approving one, so the git tools split before the write set uses them.
GIT_READ_TOOLS = ('git_status', 'git_divergence', 'git_rebase_preview')
GIT_WRITE_TOOLS = frozenset({'git_remote', 'git_checkout'})
GIT_TOOLS = (*GIT_READ_TOOLS, *sorted(GIT_WRITE_TOOLS))

#: The same fact as `is_write`, by name, for callers that only have a name.
WRITE_TOOLS = frozenset({'edit_file', 'replace_text', 'create_file', 'edit_cell', 'add_cell',
                         'run_python', 'run_shell', 'memory_forget', 'create_skill',
                         'cancel_watch', 'add_root'}) | GIT_WRITE_TOOLS
