"""What every tool result looks like, and the limits it is held to.

Docs: https://vedicreader.github.io/shalya/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['MAX_TOOL_CHARS', 'MAX_HITS', 'MAX_GREP_HITS', 'MAX_API', 'MAX_FILE', 'ERR', 'GIT_READ_TOOLS', 'GIT_WRITE_TOOLS',
           'GIT_TOOLS', 'WRITE_TOOLS', 'ACTING_TOOLS', 'Hit', 'HostError', 'host_err', 'err', 'failed', 'clip',
           'clip_lines', 'cmds', 'edits', 'apply_edits', 'diff_text', 'writes', 'is_write', 'acts', 'has_effect']

# %% ../nbs/00_core.ipynb #8ff4e050
import json
from fastcore.basics import AttrDict, listify
from fastcore.xtras import str_diff

# %% ../nbs/00_core.ipynb #9af4b779
MAX_TOOL_CHARS = 6000   # chars per tool result, budgeted for the smallest model
MAX_HITS = 20           # search hits one result carries
MAX_GREP_HITS = 60      # exact matches one `grep` returns. Part of the host contract
MAX_API = 200           # public names one `public_api` listing returns. Part of the same contract
MAX_FILE = 2_000_000    # bytes. A file larger than this is data, not source

# %% ../nbs/00_core.ipynb #53ab854f
class Hit(AttrDict):
    "One search hit: path, line, symbol, text."
    def __init__(self, path, line=1, symbol='', text=''): super().__init__(path=path, line=line, symbol=symbol, text=text)
    def __repr__(self): return f'{self.path}:{self.line}  {self.symbol}  {self.text}'

# %% ../nbs/00_core.ipynb #c55d1ed2
ERR = 'ERROR: '

class HostError(Exception): "A host refusal."

def host_err(e):
    "A caught exception, for a user-facing surface."
    return f'{type(e).__name__}: {e}'

def err(what, e=None):
    "One tool failure, spelled the way every other tool spells it."
    return f'{ERR}{what}' + (f': {host_err(e)}' if e is not None else '')

def failed(result):
    "Whether a tool result starts with `ERROR: `."
    return str(result or '').startswith(ERR)

# %% ../nbs/00_core.ipynb #a2c88077
def clip(s, n=MAX_TOOL_CHARS, more=''):
    "Truncate a tool result to `n` chars. A caller with a way to resume passes it as `more`."
    s = str(s)
    if len(s) <= n: return s
    cut = s[:n]
    nl = cut.rfind('\n')
    if nl > n * 0.6: cut = cut[:nl]
    note = f'[truncated: {len(cut)} of {len(s)} chars shown'
    return cut + f'…{note}. {more}]' if more else cut + f'…{note}]'

# %% ../nbs/00_core.ipynb #7ca20dbc
def clip_lines(lines, start=1, n=MAX_TOOL_CHARS, more='', empty='(nothing)'):
    "Render `lines` within the budget, and say which line to resume from."
    lines = listify(lines)
    if not lines: return empty
    out, used = [], 0
    for i, line in enumerate(lines):
        line = str(line)
        if used + len(line) + 1 > n:
            if out:
                rest = len(lines) - i
                tail = f'\n…[{rest} more line(s) not shown'
                hint = more.format(next=start + i) if '{next}' in more else more
                return '\n'.join(out) + (f'{tail}. {hint}]' if hint else f'{tail}]')
            keep, rest = max(1, n - 1), len(lines) - 1
            more_lines = f', and {rest} more line(s) not shown' if rest else ''
            return line[:keep] + f'\n…[line {start} is {len(line)} chars; {keep} shown{more_lines}]'
        out.append(line); used += len(line) + 1
    return '\n'.join(out)

# %% ../nbs/00_core.ipynb #d67ed39a
def cmds(commands):
    "Models emit JSON and exhash wants tuples, nested ones included: `[[...]]` becomes `[(...)]`."
    if isinstance(commands, str): commands = json.loads(commands)
    if not isinstance(commands, list): raise ValueError('commands must be a JSON list of command arrays')
    def _t(c):
        if not isinstance(c, (list, tuple)): raise ValueError(f'each command must be an array, got {type(c).__name__}')
        return tuple(_t(x) if isinstance(x, (list, tuple)) else x for x in c)
    return [_t(c) for c in commands]

# %% ../nbs/00_core.ipynb #c75c5591
def edits(es):
    "A JSON string, `{'oldText','newText'}` dicts, or `[old, new]` pairs: all three are unambiguous."
    if isinstance(es, str): es = json.loads(es)
    if isinstance(es, dict): es = [es]
    if not isinstance(es, (list, tuple)): raise ValueError('edits must be a JSON array')
    out = []
    for e in es:
        if isinstance(e, dict):
            if 'oldText' not in e or 'newText' not in e: raise ValueError("each edit needs 'oldText' and 'newText'")
            out.append((str(e['oldText']), str(e['newText'])))
        elif isinstance(e, (list, tuple)) and len(e) == 2: out.append((str(e[0]), str(e[1])))
        else: raise ValueError('each edit must be {"oldText":…,"newText":…} or [old, new]')
    return out

def apply_edits(text, es):
    "Apply exact-text edits to `text`, or raise saying which one is wrong and why."
    spans = []
    for i, (old, new) in enumerate(es, 1):
        if not old: raise ValueError(f'edit {i}: oldText is empty; use create_file to write a whole file')
        n = text.count(old)
        if n == 0: raise ValueError(f'edit {i}: oldText not found. It must match the file exactly, including indentation. Re-read the file and try again')
        if n > 1: raise ValueError(f'edit {i}: oldText matches {n} places. Include more surrounding lines so it matches exactly one')
        at = text.index(old)
        spans.append((at, at + len(old), new, i))
    spans.sort()
    for (s1, e1, _, i1), (s2, _, _, i2) in zip(spans, spans[1:]):
        if s2 < e1: raise ValueError(f'edits {i1} and {i2} overlap; merge them into one edit')
    out, at = [], 0
    for s, e, new, _ in spans:
        out.append(text[at:s])
        out.append(new)
        at = e
    out.append(text[at:])
    return ''.join(out)

# %% ../nbs/00_core.ipynb #c6041489
def diff_text(before, after, path='file'):
    "Return a unified diff."
    return str_diff(before, after, n=2, names=(f'a/{path}', f'b/{path}'))

# %% ../nbs/00_core.ipynb #399d9f51
def writes(f):
    "Mark a tool as one that changes something. `Approvals` puts these in front of a person."
    f.writes = True
    return f

def is_write(t):
    "Whether `t` is a tool that changes something."
    return bool(getattr(t, 'writes', False))

def acts(f):
    "Mark a tool that acts without writing a file the user owns."
    f.acts = True
    return f

def has_effect(t):
    "Whether `t` acts. Orthogonal to `is_write`: these are the effects approval does not gate."
    return bool(getattr(t, 'acts', False))

#: Rehearsing a merge is not approving one, so the git tools split before the write set uses them.
GIT_READ_TOOLS = ('git_status', 'git_divergence', 'git_rebase_preview')
GIT_WRITE_TOOLS = frozenset({'git_remote', 'git_checkout'})
GIT_TOOLS = (*GIT_READ_TOOLS, *sorted(GIT_WRITE_TOOLS))

#: The same fact as `is_write`, by name, for callers that only have a name.
WRITE_TOOLS = frozenset({'edit_file', 'replace_text', 'create_file', 'edit_cell', 'add_cell',
                         'run_python', 'run_shell', 'memory_forget', 'create_skill',
                         'cancel_watch', 'add_root'}) | GIT_WRITE_TOOLS

#: The same fact as `has_effect`, by name. Running code, spending money and standing work are
#: effects `WRITE_TOOLS` does not name, because none of them writes a file the user owns.
ACTING_TOOLS = frozenset({'inspect_python', 'api_call', 'generate_image', 'research',
                          'watch_url', 'set_reminder'})
