"""Every tool an agent is given, and which of them one host can actually support.

Docs: https://vedicreader.github.io/shalya/tools.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tools.ipynb.

# %% auto #0
__all__ = ['RESPONSES_API', 'IMAGE_API', 'IMAGE_MODEL', 'IMAGE_SIZES', 'API_VENDORS', 'GROUPS', 'readable', 'code_tools',
           'file_tools', 'notebook_tools', 'web_tools', 'memory_tools', 'watch_tools', 'ask_tools', 'session_tools',
           'shell_tools', 'api_tools', 'skill_tools', 'media_dir', 'mime_for', 'save_media', 'image_available',
           'api_model', 'image_tools', 'git_tools', 'tools_for', 'read_only']

# %% ../nbs/02_tools.ipynb #a71f9b84
import functools, json, mimetypes, os, re, threading, uuid
from base64 import b64decode
from pathlib import Path
from fastcore.basics import AttrDict
from fastcore.foundation import L
from fastcore.xtras import detect_mime
from .core import (Hit, ERR, MAX_TOOL_CHARS, MAX_HITS, MAX_GREP_HITS, MAX_API, GIT_TOOLS,
                         GIT_READ_TOOLS, GIT_WRITE_TOOLS, WRITE_TOOLS, clip, clip_lines, cmds,
                         edits, apply_edits, diff_text, err, failed, is_write, writes)
from .host import Host, HostError, LocalHost, host_err
from .skills import Skill, find, skill_index

# %% ../nbs/02_tools.ipynb #837ae38d
def readable(host, path, must_exist=False):
    "Resolve a path a tool is only going to read. `reading=True` is the read-outside allowance."
    return host.check(path, must_exist=must_exist, reading=True)

# %% ../nbs/02_tools.ipynb #38740e63
def code_tools(host, mx=MAX_TOOL_CHARS):
    "Seeing the code: the index, the shapes in it, and the files it covers."

    def search_code(query: str) -> str:
        """Search the codebase and every installed package for `query`.

        Semantic when the code index is built, a literal scan otherwise. Use this before
        writing anything non-trivial: the answer is usually already in the environment.
        """
        hits = host.search(query, limit=MAX_HITS)
        if not hits: return f'no matches ({host.search_note})'
        rows = []
        for h in hits:
            target = ('NOTEBOOK -- use this exact path with notebook_cells, then view_cell/edit_cell'
                      if str(h.path).lower().endswith('.ipynb')
                      else 'FILE -- use this exact path with view_file/edit_file')
            rows.append(f'{h.path}:{h.line}  {h.symbol or ""}  {h.text}\n  {target}')
        return clip(f'[{host.search_note}]\n' + '\n'.join(rows), mx)

    def similar_code(path: str, line: int = 1) -> str:
        "Find code shaped like the function at `path`:`line`. Every place a pattern was already used."
        hits = host.peers(str(readable(host, path)), int(line), limit=MAX_HITS)
        if not hits: return f'nothing similar ({host.search_note})'
        return clip('\n'.join(f'{h.path}:{h.line}  {h.symbol or ""}  {h.text}' for h in hits), mx)

    def outline(path: str) -> str:
        "The defs and classes in one file, with line numbers."
        syms = host.symbols(str(readable(host, path)))
        if not syms: return f'no symbols in {path}'
        return clip('\n'.join(f'{int(getattr(s, "score", 0))*" "}{s.line}: {s.symbol}' for s in syms), mx)

    def list_files(pattern: str = '') -> str:
        "Files in the open folders, optionally filtered by a substring of the path."
        ps = [str(p) for p in host.walk()]
        if pattern: ps = [p for p in ps if pattern.lower() in p.lower()]
        return clip_lines(ps, n=mx, more='narrow `pattern`', empty='no matching files')

    def grep(pattern: str, path_filter: str = '', regex: bool = True, ignore_case: bool = False) -> str:
        """Find every line in the open folders matching `pattern`, exactly.

        The literal counterpart to `search_code`, and not a replacement for it. Use
        `search_code` for "how does this work". It is a semantic index and it covers
        installed packages. Use `grep` when you know the string: a symbol you are about to
        rename, an error message, an import, a call site you must not miss. An index answers
        with what is *like* the query. This answers with what *is* the query, which is what
        a rename or an audit needs.

        `path_filter` is a substring of the path (`tests/`, `.py`). Set `regex=False` to
        match `pattern` literally when it contains regex punctuation.
        """
        if not str(pattern or '').strip(): return err('grep needs a pattern')
        flags = re.IGNORECASE if ignore_case else 0
        try: rx = re.compile(pattern if regex else re.escape(pattern), flags)
        except re.error as e: return err('bad pattern', e)
        # ask the host first: it may have ripgrep, and reading every file costs a `check` each
        try: fast = host.grep(pattern, path_filter=path_filter, regex=regex,
                              ignore_case=ignore_case, limit=MAX_GREP_HITS)
        except Exception: fast = None
        if fast is not None:
            if not fast: return f'no matches for {pattern!r}'
            capped = len(fast) >= MAX_GREP_HITS
            head = f'{len(fast)}{"+" if capped else ""} match(es)'
            rows = [f'{h.path}:{h.line}: {h.text}' for h in fast]
            return clip_lines([head] + rows, n=mx, more='narrow `pattern` or set `path_filter`')
        pf, hits, scanned, capped = str(path_filter or '').lower(), [], 0, False
        for p in host.walk():
            sp = str(p)
            if pf and pf not in sp.lower(): continue
            try: text = host.read(sp)
            except Exception: continue
            if not text: continue
            scanned += 1
            for i, line in enumerate(text.splitlines(), 1):
                if rx.search(line):
                    hits.append(f'{sp}:{i}: {line.strip()[:200]}')
                    if len(hits) >= MAX_GREP_HITS: capped = True; break
            if capped: break
        if not hits: return f'no matches for {pattern!r} in {scanned} file(s)'
        head = f'{len(hits)}{"+" if capped else ""} match(es) in {scanned} file(s) searched'
        return clip_lines([head] + hits, n=mx, more='narrow `pattern` or set `path_filter`')

    def ls(path: str = '') -> str:
        """List one directory: its subdirectories, then its files with sizes.

        For finding your way around. `list_files` walks everything and `grep` reads
        everything. This just says what is here, which is usually the cheaper question.
        Empty `path` lists each open folder.
        """
        roots = ([readable(host, path)] if str(path or '').strip()
                 else [host.check(r) for r in host.roots])
        out = []
        for d in roots:
            if not d.exists(): out.append(f'{d}: does not exist'); continue
            if d.is_file(): out.append(f'{d}  ({d.stat().st_size} bytes, a file)'); continue
            try: kids = sorted(d.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
            except Exception as e: out.append(err(f'cannot list {d}', e)); continue
            out.append(f'{d}/')
            for k in kids:
                if k.name.startswith('.') and k.name not in ('.agents', '.leela'): continue
                try: out.append(f'  {k.name}/' if k.is_dir() else f'  {k.name}  {k.stat().st_size}')
                except Exception: out.append(f'  {k.name}')
        return clip_lines(out, n=mx, more='name a subdirectory to list it', empty='(nothing)')

    def public_api(package: str) -> str:
        """Every public name a package exports, with its docstring and where it is defined.

        The whole surface of `package` in one call, `@patch`-added methods included, which
        reading one source file will not show. Ask before writing against an unfamiliar
        package: what you were about to implement is often already exported.
        """
        if not str(package or '').strip(): return err('public_api needs a package name')
        try: api = host.public_api(package)
        except Exception as e: return err(f'cannot list the API of {package}', e)
        if not api:
            # the index answered. This is not a missing index. Say what it does not cover
            return (f'nothing public indexed for {package!r}. The index covers installed packages and '
                    f'the open folders, not the stdlib')
        rows = [f'{h.symbol}  {h.path}:{h.line}  {h.text}' for h in api]
        return clip_lines([f'{len(rows)} public name(s) in {package}'] + rows, n=mx, more='read one with view_file')

    tools = [search_code, grep, ls, similar_code, outline, list_files]
    if host.indexed: tools.append(public_api)   # with no index it could only ever refuse
    return tools

# %% ../nbs/02_tools.ipynb #6d65593d
def file_tools(host, mx=MAX_TOOL_CHARS):
    "Reading and editing files, by exact text or by hash-verified address."

    @writes
    def add_root(path: str) -> str:
        """Open another folder, so it can be read and written like the ones already open.

        Ask for this only when the user has named a folder outside the open ones. It widens what
        you may change on their machine, so it goes to them for approval like any other write.
        """
        try: return f'opened {host.add_root(path)}. Open folders: ' + ', '.join(host.roots)
        except Exception as e: return err(f'could not open {path}', e)

    def view_file(path: str, start: int = 0, end: int = 0) -> str:
        """Read a file as `lineno|hash|content` lines. Optionally limit to lines `start`..`end`.

        Always read this way before editing: `edit_file` addresses lines by the exact
        hashes this returns. The view is also the address book.
        """
        from exhash import lnhashview, lnhashview_file
        p = readable(host, path)
        # through the host, so a host answering from somewhere other than disk -- an editor
        # holding an unsaved buffer -- is seen as itself rather than as a stale copy. The
        # hashes are the same either way: both views hash `line_hash(lineno, line)` over the
        # same lines. `replace_text` and `create_file` go through the host too; `edit_file`
        # verifies against the file, so against such a host it refuses rather than misfires
        # a host is allowed to raise from any method, and one may not implement `read` at all;
        # that is a reason to read the file, not to lose the tool
        try: text = host.read(str(p))
        except Exception: text = None
        if text is None and not p.exists(): return err(f'no such file: {p}')
        view = str(lnhashview(text, start or None, end or None) if text is not None
                   else lnhashview_file(str(p), start or None, end or None))
        return clip_lines(view.splitlines(), start=(start or 1), n=mx,
                          more='call view_file(path, start={next}) to continue')

    @writes
    def replace_text(path: str, spec: str) -> str:
        """Edit a file by exact text replacement, and return the diff. Usually the easier editor.

        `edits` is a JSON array of objects, applied together:
          [{"oldText": "def old(a):", "newText": "def new(a, b):"},
           {"oldText": "return a", "newText": "return a + b"}]

        Rules, all of them checked *before* anything is written. A rejected edit leaves
        the file exactly as it was:

        - Every `oldText` must appear **exactly once** in the file. If it appears twice,
          include more surrounding lines until it is unique. Do not guess which one.
        - Every `oldText` is matched against the file as it is **now**, not against the
          result of the earlier edits in the same call. Overlapping or nested spans are
          refused. Merge them into one edit instead.
        - Keep `oldText` as short as it can be while still unique. Do not paste a whole
          function to change one line of it.
        - An empty `oldText` is refused. To create a file use `create_file`. To append,
          include the last existing line in `oldText`.

        This and `edit_file` do the same job by different addresses: `edit_file` names
        lines by hash, which catches a stale read but costs a `view_file` before every
        edit and again after each one. Prefer this for ordinary edits. Prefer `edit_file`
        when you must be certain the line you are changing is the line you read.
        """
        p = host.check(path)
        if hasattr(host, 'check_write'): host.check_write(p)
        try: items = edits(spec)
        except Exception as e: return err('could not parse edits', e)
        if not items: return err('no edits given')
        try: before = host.read(str(p))
        except Exception as e: return err(f'could not read {p}', e)
        if before is None: return err(f'no such file: {p}. Use create_file to create it')
        try: after = apply_edits(before, items)
        except ValueError as e: return err(str(e))
        if after == before: return err('the edits changed nothing; check oldText against a fresh view_file')
        try: host.write(str(p), after)
        except Exception as e: return err('write failed', e)
        return clip(f'replaced {len(items)} block(s) in {p}\n' + diff_text(before, after, str(p)), mx)

    @writes
    def edit_file(path: str, commands: str) -> str:
        """Edit a file with hash-verified exhash commands, and return the diff.

        `commands` is a JSON array of command arrays, each starting with an address taken
        from `view_file`, e.g.
          [["12|a1b2|", "s", "old text", "new text"],
           ["30|9f3c|", "a", "a new line appended after line 30"]]
        Every address's hash is checked immediately before it runs. An edit built on a
        stale view fails instead of damaging the wrong line. Nothing is written unless
        every command succeeds.
        """
        from exhash import file_exhash
        p = host.check(path)
        if hasattr(host, 'check_write'): host.check_write(p)
        try: cs = cmds(commands)
        except Exception as e: return err('could not parse commands', e)
        if not cs: return err('no commands given')
        try: return clip(str(file_exhash(str(p), *cs)), mx)
        except Exception as e: return err('edit failed', e)

    @writes
    def create_file(path: str, text: str = '') -> str:
        "Create (or overwrite) a whole file. For changes to an existing file prefer `replace_text`."
        try: return f'wrote {host.write(path, text)}'
        except Exception as e: return err('write failed', e)

    return [view_file, replace_text, edit_file, create_file, add_root]

# %% ../nbs/02_tools.ipynb #3c171dfb
def notebook_tools(host, mx=MAX_TOOL_CHARS):
    "Notebooks, addressed by cell id rather than by line."

    def notebook_cells(path: str) -> str:
        "List a notebook's cells: id, type, and first line. Cell ids are what `edit_cell` addresses."
        try: rows = host.nb_cells(str(readable(host, path)))
        except NotImplementedError: raise
        except Exception as e: return err('could not read notebook', e)
        return clip('\n'.join(f'{i}  {t:8} {(s or "").strip().splitlines()[0][:100] if (s or "").strip() else ""}'
                              for i, t, s in rows) or '(empty notebook)')

    def view_cell(path: str, cell_id: str) -> str:
        "Read one notebook cell as `lineno|hash|content` lines, ready to address with `edit_cell`."
        from exhash import lnhashview_cell
        try: return clip(str(lnhashview_cell(str(readable(host, path)), cell_id)))
        except Exception as e: return err('could not read cell', e)

    @writes
    def edit_cell(path: str, cell_id: str, commands: str) -> str:
        "Edit one notebook cell's source with exhash commands from `view_cell`. Same format as `edit_file`."
        from exhash import cell_exhash
        try: cs = cmds(commands)
        except Exception as e: return err('could not parse commands', e)
        try: return clip(str(cell_exhash(str(host.check(path)), cell_id, *cs)))
        except Exception as e: return err('edit failed', e)

    @writes
    def add_cell(path: str, source: str, index: int = -1, cell_type: str = 'code') -> str:
        "Insert a new cell into a notebook at `index` (-1 appends). Creates the notebook if needed."
        try: return f'added cell {host.nb_add_cell(str(host.check(path)), source, int(index), cell_type)} to {path}'
        except NotImplementedError: raise
        except Exception as e: return err('could not add cell', e)

    return [notebook_cells, view_cell, edit_cell, add_cell]

# %% ../nbs/02_tools.ipynb #68bb2099
def web_tools(host, mx=MAX_TOOL_CHARS):
    "The web, for the questions whose answer depends on current documentation."

    def web_search(query: str) -> str:
        "Search the web. Returns titles and urls. Follow up with `read_url` on the useful ones."
        docs = host.web_search(query, n=MAX_HITS)
        if not docs: return f'no results ({host.research_note})'
        return clip('\n'.join(f'{d.title}\n  {d.url}' for d in docs))

    def read_url(url: str, remember: bool = True) -> str:
        """Read one web page as markdown. A GitHub file, an arxiv paper or a YouTube
        transcript is read as what it is rather than as the page around it.

        It enters durable research memory by default. Pass `remember=False` for sensitive,
        obviously irrelevant, or exploratory results that should remain ephemeral.
        """
        d = host.read_url(url, remember=remember)
        return clip(d.text if d else f'could not read {url} ({host.research_note})')

    def research(query: str) -> str:
        "Search the web and read the top results into one cited digest. Slower than `web_search`. Use for depth."
        return clip(host.research(query) or f'nothing found ({host.research_note})')

    return [web_search, read_url, research]

# %% ../nbs/02_tools.ipynb #13dd6936
def memory_tools(host, mx=MAX_TOOL_CHARS):
    "Durable pages and research recalled as document sections rather than flat snippets."

    def memory_search(query: str, limit: int = 8) -> str:
        """Search pages remembered from earlier reads and research.

        Returns whole operative sections with breadcrumbs plus related semantic paths. Use
        this before searching the live web when the question may have been researched before.
        """
        try: return clip(json.dumps(host.memory_search(query, int(limit)), default=str), MAX_TOOL_CHARS * 2)
        except Exception as e: return err('memory search failed', e)

    def memory_tree(document: str = '') -> str:
        """Browse remembered document headings without embedding a query.

        `document` may be a title substring or stable document id. Leave it empty to list
        all remembered roots, then call again with the relevant document.
        """
        try: return clip(json.dumps(host.memory_tree(document), default=str), MAX_TOOL_CHARS * 2)
        except Exception as e: return err('memory tree failed', e)

    def memory_read(node_id: str) -> str:
        "Read one whole remembered section by the node id returned by memory_search/tree."
        try: return clip(json.dumps(host.memory_read(node_id), default=str), MAX_TOOL_CHARS * 3)
        except Exception as e: return err('memory read failed', e)

    def memory_topics(limit: int = 12) -> str:
        "Map remembered material into labelled semantic clusters and representative members."
        try: return clip(json.dumps(host.memory_topics(int(limit)), default=str), MAX_TOOL_CHARS * 2)
        except Exception as e: return err('memory topics failed', e)

    @writes
    def memory_forget(doc_id: str) -> str:
        """Purge one bad, sensitive, stale or irrelevant remembered document by id.

        This removes its tree, chunks and ANN entries. Use only when the user requests it. Do not silently curate their memory.
        """
        try: return 'forgot document' if host.memory_forget(doc_id) else 'document was not forgotten'
        except Exception as e: return err('memory purge failed', e)

    return [memory_search, memory_tree, memory_read, memory_topics, memory_forget]

# %% ../nbs/02_tools.ipynb #e919c44b
def watch_tools(host, mx=MAX_TOOL_CHARS):
    "Standing interests: what to put back on the desk later, and what has come due now."

    def remember(text: str, title: str = '', tags: str = '') -> str:
        """Write a conclusion into durable memory so a later session finds it.

        For what you worked out, not for what you read. `read_url` already files pages.
        `tags` is a comma-separated list.
        """
        try:
            d = host.remember(text, title=title or None,
                              tags=[t.strip() for t in tags.split(',') if t.strip()])
            return f"remembered {d.get('title')!r} as {d.get('doc_id')}"
        except Exception as e: return err('could not remember', e)

    def set_reminder(text: str, every: str = '1w', note: str = '') -> str:
        """Come back to `text` every `every` ('30m', '6h', '1d', '1w').

        The reminder files itself into memory when it comes due. It surfaces in
        `memory_search` and in `poll_watches` rather than needing a notification channel.
        """
        try:
            w = host.watch(text, action='remind', every=every, note=note or None)
            return f"reminder {w['id']} set, every {every}"
        except Exception as e: return err('could not set reminder', e)

    def watch_url(url: str, every: str = '1d', note: str = '') -> str:
        "Re-read `url` every `every` and file each version in memory. Changes are visible over time."
        try:
            w = host.watch(url, action='url', every=every, note=note or None)
            return f"watching {url} as {w['id']}, every {every}"
        except Exception as e: return err('could not watch', e)

    def list_watches(due_only: bool = False) -> str:
        "Every standing watch and reminder, soonest first. `due_only` shows just what has come due."
        try:
            ws = host.watches(due_only=bool(due_only))
            if not ws: return 'nothing is being watched'
            return clip('\n'.join(
                f"{w['id']}  {w['action']:8} every {int(w['every'])}s  runs={w['runs']}"
                f"  {w.get('last_status') or 'never run'}  {str(w['target'])[:80]}" for w in ws))
        except Exception as e: return err('could not list watches', e)

    @writes
    def cancel_watch(watch_id: str) -> str:
        "Delete one watch by id. Only when the user asks. Do not silently curate their reminders."
        try:
            host.unwatch(watch_id)
            return f'cancelled {watch_id}'
        except Exception as e: return err('could not cancel', e)

    def poll_watches() -> str:
        """Run every watch that has come due, and report what fired.

        Call this when the user asks what is outstanding, or at the start of a session.
        Anything that fired is now in memory: follow up with `memory_search`.
        """
        try:
            r = host.poll()
            if not r.get('ran'): return f"nothing due ({r.get('checked', 0)} watched)"
            lines = [f"{x['status']:7} {x['action']:8} {str(x['target'])[:90]}" for x in r['results']]
            return clip(f"{r['ran']} of {r['checked']} fired\n" + '\n'.join(lines))
        except Exception as e: return err('poll failed', e)

    return [remember, set_reminder, watch_url, list_watches, cancel_watch, poll_watches]

# %% ../nbs/02_tools.ipynb #27b30123
def ask_tools(host, mx=MAX_TOOL_CHARS):
    "One tool, and its own group: answering out of memory takes a model, and a store is not one."

    def ask_memory(question: str, document: str = '', instruction: str = '') -> str:
        """Ask remembered research a question and get a short cited answer, not the sections.

        Prefer this to `memory_search` when you want an answer rather than material: the search
        returns whole sections into your context and this returns a paragraph, which is the same
        trade `delegate_search` makes. `document` narrows it to one remembered document by title
        or id.

        Some of what the vault holds is private. A statement, a medical letter, an exported
        chat. Those are answered by a model on this machine that is instructed not to repeat any
        personal detail to you. What you get back is shape and quantity: how many, what kind,
        which period, whether two things agree. It will tell you what it is holding and what
        instruction would let it answer usefully. Send that back as `instruction` and it gets
        another turn on the same material.

        Do not ask it for the details it withheld, or ask it to relay them "for the user". It
        will refuse, and the refusal is the point rather than an obstacle.
        """
        try: r = host.ask(question, ref=document or None, instruction=instruction)
        except NotImplementedError: raise
        except Exception as e: return err('could not ask memory', e)
        rows = [str(r.get('answer') or '(no answer)')]
        if (p := r.get('pii')) and p.get('has_pii'):
            rows.append(f"\n[answered on a local model; it holds back "
                        f"{', '.join(sorted(p.get('identifying') or {}))}. Reply with `instruction=` "
                        f"to say what you need -- a count, a total, a comparison, a yes or no.]")
        if (c := r.get('cited')):
            rows.append('\n' + '\n'.join(f"[{x['n']}] {x['breadcrumb']}  ({x['node_id']})" for x in c))
        return clip('\n'.join(rows), MAX_TOOL_CHARS * 2)

    return [ask_memory]

# %% ../nbs/02_tools.ipynb #5632a9ae
def session_tools(host, mx=MAX_TOOL_CHARS):
    "The live kernel the user is working in, and the terminal they are looking at."

    def list_vars() -> str:
        "List the variables visible in the user's live session: name, type, and a short value."
        return clip(host.list_vars() or '(empty session)')

    @writes
    def run_python(code: str) -> str:
        """Run Python in the user's live kernel namespace.

        Read any variable freely. Bind results to NEW names so they survive to the next
        call. Mutating or deleting the user's variables is refused. Rebind instead
        (`df2 = df.drop(...)`). Call `list_vars` first if you do not know what is there.
        """
        try: return clip(host.run_python(code))
        except NotImplementedError: raise
        except Exception as e: return err('run failed', e)

    def inspect_python(code: str, scope: str = 'isolated') -> str:
        """Look at the user's live variables by running Python that cannot change them.

        Two scopes. Both leave the user's variables exactly as they were. They differ in
        how much Python you get. Pick by what the question needs:

        - `scope='isolated'` (default) runs in an allowlist sandbox on a copy. Attribute
          reads and builtins work. `df.shape`, `len(df)`, `type(x).__name__`. And most
          library method calls are refused. Costs nothing to be wrong about.
        - `scope='overlay'` runs the real interpreter against the real namespace. Library
          calls work: `list(df.columns)`, `df.head(3).to_dict()`, `model.summary()`. Names
          you bind persist into your own layer for later calls. You still cannot delete,
          rebind or mutate anything the user made. That is refused, with an explanation.

        Start isolated. Move to overlay when the sandbox refuses something you need. Neither
        needs approval, and both run while one of the user's cells is still going. For work
        that must land in the *user's* namespace, use `run_python` instead.
        """
        try: return clip(host.inspect_python(code, scope=scope))
        except NotImplementedError: raise
        except Exception as e: return err('inspection failed', e)

    def read_terminal(lines: int = 200) -> str:
        """Read what the IDE's terminal has printed. A failing build, a stack trace, a test run.

        This is *read only*: it shows what the user ran, and cannot run anything. Use it
        when they mention an error they are looking at rather than asking them to paste it.
        """
        return clip(host.terminal_text(int(lines)) or 'the terminal has printed nothing yet')

    # No tool per recipe: `run_python` composes one in a line. See `coding_patterns`.
    return [list_vars, run_python, inspect_python, read_terminal]

# %% ../nbs/02_tools.ipynb #0eb6a349
def shell_tools(host, mx=MAX_TOOL_CHARS):
    "Running a command, which is the only way to find out whether the work is done."

    @writes
    def run_shell(command: str, cwd: str = '', timeout: int = 120) -> str:
        """Run one shell command in the project and return its exit code and output.

        This is how you check your work, and you are expected to use it: after an edit, run
        the tests. After a change to a signature, run the type checker or the linter the
        project already uses. Before saying something passes, make it pass here. A claim
        with no command behind it is a guess, and will be read as one.

        - stdout and stderr come back interleaved, as a person would see them, with the
          exit code on the first line. A non-zero exit is a *result*: read the output and
          fix the cause, do not run it again unchanged.
        - `cwd` defaults to the first open folder and must stay inside the open folders.
        - `timeout` is in seconds. The command is killed when it expires. Do not start
          servers, watchers, REPLs, or anything else that does not exit on its own.
        - Use the project's own commands. The ones in its README, `pyproject.toml`, or
          `Makefile`. Rather than a global tool that may not be what it uses.
        - This may be put to the user for approval. Send one purposeful command rather
          than a chain of exploratory ones.
        """
        cmd = str(command or '').strip()
        if not cmd: return err('no command given')
        try: code, out = host.run_cmd(cmd, cwd=(str(cwd).strip() or None), timeout=int(timeout))
        except NotImplementedError: raise
        except Exception as e: return err('command could not be run', e)
        head = f'exit {code}' + ('' if code == 0 else '  (command FAILED)')
        body = clip((out or '').rstrip() or '(no output)', mx - 200,
                    more='re-run narrowing the command (a single test, `| tail -50`) rather than repeating it')
        return f'{head}\n{body}' if code == 0 else f'{ERR}{head}\n{body}'

    return [run_shell]

# %% ../nbs/02_tools.ipynb #80208a7b
def api_tools(host, mx=MAX_TOOL_CHARS):
    "Read an API specification, browse what it declares, and call one operation."

    def api_load(src: str, name: str = '') -> str:
        """Load an OpenAPI or discovery document from a url or a path.

        Do this before `api_ops` or `api_call`. `src` is often `<host>/openapi.json`. Returns
        the operation count and the groups, which is what to narrow by next.
        """
        try: return clip(json.dumps(host.api_load(src, name), default=str), mx)
        except Exception as e: return err('could not load the spec', e)

    def api_ops(group: str = '', name: str = '', match: str = '', offset: int = 0) -> str:
        """List the operations a loaded spec declares, with their signatures.

        Narrow with `group` or `match` first: a real API has hundreds of operations, and
        reading all of them is not how you find the one you want. One page comes back at a
        time. `api_load` says how many there are in total, and `offset` walks the rest.
        """
        try:
            rows = host.api_ops(group, name, match, offset=offset)
            total = host.api_count(group=group, name=name, match=match)
            out = {'operations': rows}
            if offset or len(rows) < total:
                out |= {'matched': total, 'showing': f'{offset + 1}-{offset + len(rows)}',
                        'more': f'call again with offset={offset + len(rows)}'} if offset + len(rows) < total else {'matched': total}
            return clip(json.dumps(out, default=str), mx)
        except Exception as e: return err('could not read the operations', e)

    def api_call(operation: str, name: str = '', params: dict = None) -> str:
        """Call one operation, passing `params` under the names `api_ops` reported.

        A parameter the operation does not declare is an error rather than an extra query
        field, which is what makes a wrong call fail loudly instead of quietly.
        """
        try: return clip(json.dumps(host.api_call(operation, name, **(params or {})), default=str), mx)
        except Exception as e: return err(f'{operation} failed', e)

    return [api_load, api_ops, api_call]

# %% ../nbs/02_tools.ipynb #6ae4e312
def skill_tools(host, get_skills, mx=MAX_TOOL_CHARS):
    "Reading discovered skills and creating project-local Agent Skills."

    def read_skill(name: str) -> str:
        """Read one skill in full: how to use a tool or a library that is already installed here.

        The skill list in your briefing gives names and one-line descriptions. Read the
        matching one *before* doing the work it describes, not after it has gone wrong.
        """
        ss = get_skills()
        s = find(ss, name)
        if s is None:
            return f'no skill matching {name!r}. Available: ' + ', '.join(x.name for x in ss)
        return clip(f'<skill name="{s.name}" from="{s.where}">\n{s.text()}\n</skill>', MAX_TOOL_CHARS * 3)

    @writes
    def create_skill(name: str, description: str, instructions: str) -> str:
        """Create a reusable project skill at `.agents/skills/NAME/SKILL.md`.

        Use this only when the user asks to preserve repeatable project know-how as a
        skill, not for ordinary task notes. `name` must be lowercase kebab-case. `description` says when it applies. `instructions` is the complete Markdown body.
        Existing skills are never overwritten. Run `/reload` after creation to make the
        current agent advertise it immediately.
        """
        from pathlib import Path
        name = str(name or '').strip()
        if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', name):
            return 'skill name must be lowercase kebab-case (for example, notebook-tests)'
        if not str(description or '').strip(): return 'skill description is required'
        if not str(instructions or '').strip(): return 'skill instructions are required'
        roots = list(host.roots or ())
        if not roots: return 'open a project folder before creating a skill'
        target = Path(host.check(Path(roots[0])/'.agents'/'skills'/name/'SKILL.md'))
        exists = target.exists()
        if not exists:
            try: exists = host.read(str(target)) is not None
            except Exception: pass
        if exists: return f'refusing to overwrite existing skill: {target}'
        title = json.dumps(name, ensure_ascii=False)
        desc = json.dumps(' '.join(str(description).split()), ensure_ascii=False)
        text = f'---\nname: {title}\ndescription: {desc}\n---\n\n{str(instructions).strip()}\n'
        try: host.write(str(target), text)
        except Exception as e: return err('could not create skill', e)
        return f'created {target}; run /reload to load it into the current agent'

    return [read_skill, create_skill]

# %% ../nbs/02_tools.ipynb #8e7cc301
RESPONSES_API = 'https://api.openai.com/v1/responses'
IMAGE_API = 'https://api.openai.com/v1/images/generations'
IMAGE_MODEL = 'gpt-image-1'
IMAGE_SIZES = ('1024x1024', '1536x1024', '1024x1536', 'auto')
API_VENDORS = ('openai/', 'azure/')

# %% ../nbs/02_tools.ipynb #14d82ec8
def media_dir(session=''):
    "Where a turn's generated pictures are kept: beside the session record that produced them."
    d = Path(session or '.') / 'media'
    d.mkdir(parents=True, exist_ok=True)
    return d

def mime_for(path):
    "The mime a saved picture is: what its bytes say, else what its name does."
    try: m = detect_mime(Path(path).read_bytes()[:64])
    except OSError: m = None
    return m or mimetypes.guess_type(str(path))[0] or 'image/png'

def save_media(m, session='', stem='image'):
    "One `{'mime','data'}` from `Resp.media` written under the session, as a `Path`."
    mime = m.get('mime') or 'image/png'
    ext = mimetypes.guess_extension(mime) or '.' + mime.split('/')[-1]
    d = media_dir(session)
    n = 1 + len(list(d.glob(f'{stem}-*')))
    p = d / f'{stem}-{n}{ext}'
    p.write_bytes(m['data'])
    return p

def image_available(): return bool(os.environ.get('OPENAI_API_KEY'))

def _hdrs(): return {'Authorization': f"Bearer {os.environ['OPENAI_API_KEY']}"}

def _post_image(prompt, size, n, timeout=120, model=IMAGE_MODEL):
    "Raw `data` rows from the images endpoint."
    import httpx
    r = httpx.post(IMAGE_API, timeout=timeout, headers=_hdrs(),
                   json={'model': model, 'prompt': prompt, 'size': size, 'n': n})
    r.raise_for_status()
    return r.json().get('data') or []

def api_model(model):
    "A spec's `model_id` as the OpenAI endpoints spell it."
    s = str(model or '')
    for v in API_VENDORS:
        if s.startswith(v): return s[len(v):]
    return s

def _post_responses(prompt, model, timeout=300):
    "The untouched Responses reply from `model` drawing through its built-in image tool."
    import httpx
    r = httpx.post(RESPONSES_API, timeout=timeout, headers=_hdrs(),
                   json={'model': api_model(model), 'input': prompt,
                         'tools': [{'type': 'image_generation'}]})
    r.raise_for_status()
    return r.json()

# %% ../nbs/02_tools.ipynb #7a99e2b6
def image_tools(host, mx=MAX_TOOL_CHARS, session='', draws_itself=None, from_reply=None, model_id='',
                on_media=None):
    "Drawing: by the turn's own model where it can, and by the images endpoint where it cannot."

    def generate_image(prompt: str, size: str = '1024x1024', n: int = 1, model: str = '') -> str:
        """Generate a picture from a description and save it. Returns the paths written.

        Use whenever the user asks for an image. `size` is one of 1024x1024, 1536x1024,
        1024x1536, or auto. Set `model` to use the dedicated images endpoint.
        """
        if not image_available(): return err('image generation is unavailable', 'OPENAI_API_KEY is not set')
        if size not in IMAGE_SIZES: return err('unknown size', f'{size!r}; use one of {", ".join(IMAGE_SIZES)}')
        own = bool(draws_itself and draws_itself() and from_reply and model_id)
        try:
            if not model and own: media = from_reply(_post_responses(prompt, model_id))
            else: media = [{'mime': 'image/png', 'data': b64decode(r['b64_json'])}
                           for r in _post_image(prompt, size, max(1, min(int(n or 1), 4)),
                                                model=api_model(model or IMAGE_MODEL))
                           if r.get('b64_json')]
        except Exception as e: return err('could not generate the image', e)
        if not media: return err('the model returned no image', 'the reply carried no picture')
        try: out = [save_media(m, session, 'generated') for m in media]
        except Exception as e: return err('could not save the image', e)
        if on_media: on_media(out)
        return clip('\n'.join(str(p) for p in out))

    return [generate_image]

# %% ../nbs/02_tools.ipynb #49342acf
from gheasy.repo import GitRepo, STATE_KEYS, REMOTE_OPS, _said

def git_tools(host, mx=MAX_TOOL_CHARS):
    "Git bound to one open repository, kept inside the host's roots."
    def repo(path=''):
        roots = L(host.roots).map(lambda r: Path(r).expanduser().resolve())
        if not roots: raise ValueError('open a project folder first')
        found = GitRepo.at(host.check(path or getattr(host, 'project', '') or roots[0], must_exist=True))
        if not any(found.root.is_relative_to(r) for r in roots):
            raise ValueError(f'Git root {found.root} is outside the open folders; open the repository root first')
        return found
    def state(r, result=''): return {'result': result} | {k: r.info()[k] for k in STATE_KEYS}
    def answer(what, path, make):
        try: return clip(json.dumps(make(repo(path)), indent=2), mx * 2)
        except Exception as e: return err(what, e)
    def preview(r, onto):
        oid = r._resolve_ref(onto)
        stops, replayed, _ = r._replay(oid, list(reversed(r.history(limit=250, ref=f'{oid}..HEAD'))))
        return ({k: v for k, v in r.rebase_preview(onto).items() if k != 'review'}
                | {'stops_at': stops, 'replayed': replayed})
    def git_status(path: str = '') -> str:
        "Repository status: branch, upstream, local and remote branches, and changed files."
        return answer('git status', path, state)
    def git_divergence(path: str = '', upstream: str = '') -> str:
        "How far this branch has run from its upstream each way, and every way back, rehearsed."
        return answer('git divergence', path, lambda r: r.divergence(upstream))
    def git_rebase_preview(onto: str, path: str = '') -> str:
        "What replaying this branch onto `onto` would hit, without rewriting anything."
        return answer('git rebase preview', path, lambda r: preview(r, onto))
    @writes
    def git_remote(op: str = 'fetch', path: str = '') -> str:
        "Talk to the remote: `fetch`, `pull` (fast-forward only), or `push`."
        if op not in REMOTE_OPS: return err('git remote', ValueError(f'op must be one of {", ".join(REMOTE_OPS)}'))
        return answer(f'git {op}', path, lambda r: state(r, _said(getattr(r, op)())))
    @writes
    def git_checkout(branch: str, path: str = '') -> str:
        "Switch to a local branch, or create a local tracking branch from `REMOTE/BRANCH`."
        return answer('git checkout', path, lambda r: state(r, _said(r.checkout(str(branch or '').strip()))))
    return [git_status, git_divergence, git_rebase_preview, git_remote, git_checkout]

# %% ../nbs/02_tools.ipynb #8cc4fdac
#: group -> the factory that builds it. Order is the order a model sees the tools in.
GROUPS = (('code', code_tools), ('file', file_tools), ('notebook', notebook_tools),
          ('web', web_tools), ('memory', memory_tools), ('ask', ask_tools),
          ('watch', watch_tools),
          ('api', api_tools), ('session', session_tools), ('shell', shell_tools),
          ('git', git_tools))

def tools_for(host, get_skills=None, extra=(), mx=MAX_TOOL_CHARS, drop=(), image=None):
    """Every tool this host declares it can support, plus whatever else was registered.

    `image` is a built image group, or None. It needs to know what the turn's model can do, and a
    host does not, so the frontend that knows builds it and passes it in.
    """
    drop = set(drop or ())
    tools = [t for g, f in GROUPS if g not in drop and host.can(g) for t in f(host, mx)]
    if get_skills is not None and 'skill' not in drop: tools += skill_tools(host, get_skills, mx)
    if image is not None and 'image' not in drop: tools += list(image)
    return tools + list(extra or ())

# %% ../nbs/02_tools.ipynb #01e94cbe
def read_only(tools, max_calls=None, writes=False, block=()):
    "The tools a sub-agent may have, optionally behind a hard per-task call budget."
    blocked = set(block or ())
    allowed = [t for t in tools if getattr(t, '__name__', '') not in blocked and (writes or not is_write(t))]
    if max_calls is None: return allowed
    state, lock = {'n': 0}, threading.Lock()

    def guarded(f):
        @functools.wraps(f)
        def call(*args, **kw):
            with lock:
                state['n'] += 1
                over = state['n'] > max_calls
            if over:
                return ('Sub-agent tool budget exhausted. Stop calling tools and return the '
                        'best evidence-backed answer now.')
            return f(*args, **kw)
        return call
    return [guarded(t) for t in allowed]
