"""Every tool an agent is given, and which of them one host can actually support.

Docs: https://vedicreader.github.io/shalya/tools.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tools.ipynb.

# %% auto #0
__all__ = ['KINDS', 'RESPONSES_API', 'IMAGE_API', 'IMAGE_MODEL', 'IMAGE_SIZES', 'API_VENDORS', 'GROUPS', 'readable', 'resolved',
           'code_tools', 'file_tools', 'exhash_tools', 'notebook_tools', 'web_tools', 'research_tools', 'memory_tools',
           'watch_tools', 'ask_tools', 'session_tools', 'shell_tools', 'api_tools', 'skill_tools', 'author_tools',
           'media_dir', 'mime_for', 'save_media', 'image_available', 'api_model', 'image_tools', 'git_tools',
           'tools_for', 'tool_groups', 'group_of', 'read_only']

# %% ../nbs/02_tools.ipynb #a71f9b84
import functools, json, mimetypes, os, re, shlex, threading, uuid
from base64 import b64decode
from fnmatch import fnmatch
from pathlib import Path
from exhash import lnhashview, lnhashview_file, file_exhash
from fastcore.basics import AttrDict, bind
from fastcore.foundation import L
from fastcore.xtras import detect_mime
from .core import (Hit, ERR, MAX_TOOL_CHARS, MAX_HITS, MAX_GREP_HITS, MAX_API, GIT_TOOLS,
                         GIT_READ_TOOLS, GIT_WRITE_TOOLS, WRITE_TOOLS, clip, clip_lines, cmds,
                         edits, apply_edits, diff_text, err, failed, attempt, is_write, writes, acts, has_effect,
                         ACTING_TOOLS, summary, summarise, one_line as _1)
from .host import (Host, HostError, LocalHost, host_err, CodeHost, WebHost, NotebookHost,
                         MemoryHost, AskHost, WatchHost, SessionHost, ShellHost, ApiHost, GitHost)
from .skills import Skill, find, skill_index

# %% ../nbs/02_tools.ipynb #837ae38d
def readable(host, path, must_exist=False):
    "Resolve a path a tool is only going to read. `reading=True` is the read-outside allowance."
    return host.check(path, must_exist=must_exist, reading=True)

def resolved(host, path, writing=False, reading=False, must_exist=False):
    "`(path, '')`, or `(None, err)` when the host refuses it: raising would end the turn."
    try:
        p = readable(host, path, must_exist) if reading else host.check(path, must_exist=must_exist)
        if writing and hasattr(host, 'check_write'): host.check_write(p)
        return p, ''
    except Exception as e: return None, err(f'cannot use {path}', e)

# %% ../nbs/02_tools.ipynb #38740e63
def code_tools(host, mx=MAX_TOOL_CHARS):
    "Code search and structure tools."

    @summary(lambda a: f'Search {_1(a.get("query"))}')
    def search_code(query: str) -> str:
        "Search the open folders and installed packages for `query`: semantic when an index is ready, literal otherwise."
        hits = host.search(query, limit=MAX_HITS)
        if not hits: return f'no matches ({host.search_note})'
        rows = []
        for h in hits:
            target = ('NOTEBOOK -- use this exact path with notebook_cells, then view_cell/edit_cell'
                      if str(h.path).lower().endswith('.ipynb')
                      else 'FILE -- use this exact path with view_file/edit_file')
            rows.append(f'{h.path}:{h.line}  {h.symbol or ""}  {h.text}\n  {target}')
        return clip(f'[{host.search_note}]\n' + '\n'.join(rows), mx)

    @summary(lambda a: f'Similar to {a.get("path","")}:{a.get("line", 1)}')
    def similar_code(path: str, line: int = 1) -> str:
        "Find implementations similar to the function at `path`:`line`."
        p, refused = resolved(host, path, reading=True)
        if refused: return refused
        hits = host.peers(str(p), int(line), limit=MAX_HITS)
        if not hits: return f'nothing similar ({host.search_note})'
        return clip('\n'.join(f'{h.path}:{h.line}  {h.symbol or ""}  {h.text}' for h in hits), mx)

    @summary(lambda a: f'Outline {a.get("path","")}')
    def outline(path: str) -> str:
        "The defs and classes in one file, with line numbers."
        p, refused = resolved(host, path, reading=True)
        if refused: return refused
        syms = host.symbols(str(p))
        if not syms: return f'no symbols in {path}'
        return clip('\n'.join(f'{int(getattr(s, "score", 0))*" "}{s.line}: {s.symbol}' for s in syms), mx)

    @summary(lambda a: f'Grep {_1(a.get("pattern",""))}' + (f' in {a["path_filter"]}' if a.get('path_filter') else ''))
    def grep(pattern: str, path_filter: str = '', regex: bool = True, ignore_case: bool = False) -> str:
        "Lines matching `pattern` in the open folders; `path_filter` is a path substring; `regex=False` matches literally."
        if not str(pattern or '').strip(): return err('grep needs a pattern')
        flags = re.IGNORECASE if ignore_case else 0
        try: rx = re.compile(pattern if regex else re.escape(pattern), flags)
        except re.error as e: return err('bad pattern', e)
        try: fast = host.grep(pattern, path_filter=path_filter, regex=regex, ignore_case=ignore_case, limit=MAX_GREP_HITS)
        except Exception: fast = None
        if fast is not None:
            if not fast: return f'no matches for {pattern!r}'
            capped = len(fast) >= MAX_GREP_HITS
            head = f'{len(fast)}{"+" if capped else ""} match(es)'
            rows = [f'{h.path}:{h.line}: {h.text}' for h in fast]
            return clip_lines([head] + rows, n=mx, more='narrow `pattern` or set `path_filter`')
        pf, hits, scanned, capped = str(path_filter or '').lower(), [], 0, False
        for p in host.walk():
            sp = str(p)
            if pf and pf not in sp.lower(): continue
            try: text = host.read(sp)
            except Exception: continue
            if not text: continue
            scanned += 1
            for i, line in enumerate(text.splitlines(), 1):
                if rx.search(line):
                    hits.append(f'{sp}:{i}: {line.strip()[:200]}')
                    if len(hits) >= MAX_GREP_HITS: capped = True; break
            if capped: break
        if not hits: return f'no matches for {pattern!r} in {scanned} file(s)'
        head = f'{len(hits)}{"+" if capped else ""} match(es) in {scanned} file(s) searched'
        return clip_lines([head] + hits, n=mx, more='narrow `pattern` or set `path_filter`')

    @summary(lambda a: f'List {a.get("path") or "(open folders)"}' + (f' matching {a["pattern"]}' if a.get('pattern') else ''))
    def ls(path: str = '', pattern: str = '', recursive: bool = False) -> str:
        "List a folder (each open root when empty): subfolders first, then files with sizes; `pattern` filters names, `recursive` walks."
        if str(path or '').strip():
            p, refused = resolved(host, path, reading=True)
            if refused: return refused
            roots = [p]
        else: roots = [host.check(r) for r in host.roots]
        pat = str(pattern or '').lower()
        hit = (lambda s: fnmatch(s.lower(), pat)) if any(c in pat for c in '*?[') else (lambda s: pat in s.lower())
        if recursive:
            ps = [str(f) for f in host.walk() if any(Path(f).is_relative_to(r) for r in roots) and (not pat or hit(Path(f).name) or hit(str(f)))]
            return clip_lines(ps, n=mx, more='narrow `pattern`', empty='no matching files')
        out = []
        for d in roots:
            if not d.exists(): out.append(f'{d}: does not exist'); continue
            if d.is_file(): out.append(f'{d}  ({d.stat().st_size} bytes, a file)'); continue
            try: kids = sorted(d.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
            except Exception as e: out.append(err(f'cannot list {d}', e)); continue
            out.append(f'{d}/')
            for k in kids:
                if k.name.startswith('.') and k.name not in ('.agents', '.leela'): continue
                if pat and not hit(k.name): continue
                try: out.append(f'  {k.name}/' if k.is_dir() else f'  {k.name}  {k.stat().st_size}')
                except Exception: out.append(f'  {k.name}')
        return clip_lines(out, n=mx, more='name a subdirectory to list it', empty='(nothing)')

    @summary(lambda a: f'Public API of {a.get("package","?")}')
    def public_api(package: str) -> str:
        "Every public name a package exports, with its docstring and where it is defined."
        if not str(package or '').strip(): return err('public_api needs a package name')
        try: api = host.public_api(package)
        except Exception as e: return err(f'cannot list the API of {package}', e)
        if not api: return (f'nothing public indexed for {package!r}. covers installed packages and open folders, not stdlib')
        rows = [f'{h.symbol}  {h.path}:{h.line}  {h.text}' for h in api]
        return clip_lines([f'{len(rows)} public name(s) in {package}'] + rows, n=mx, more='read one with view_file')

    tools = [search_code, grep, ls, outline]
    if getattr(host, 'indexed', False): tools += [similar_code, public_api]
    return tools

# %% ../nbs/02_tools.ipynb #6d65593d
def _replace(read, es, what=''):
    "`(after, before, n, '')` for exact-text edits to the text `read()` returns, or `(None, None, 0, err)` with the reason."
    try: items = edits(es)
    except Exception as e: return None, None, 0, err('could not parse edits', e)
    if not items: return None, None, 0, err('no edits given')
    try: before = read()
    except Exception as e: return None, None, 0, err(f'could not read {what}'.rstrip(), e)
    if before is None: return None, None, 0, err(f'no such file: {what}; create_file makes one')
    try: after = apply_edits(before, items)
    except ValueError as e: return None, None, 0, err(str(e))
    if after == before: return None, None, 0, err('the edits changed nothing; check oldText against a fresh view')
    return after, before, len(items), ''

def file_tools(host, mx=MAX_TOOL_CHARS):
    "Reading and editing files by exact text. Read-only where the host cannot write."

    @writes
    @summary(lambda a: f'Open folder {a.get("path","")}')
    def add_root(path: str) -> str:
        "Add an existing folder the user named to the read and write boundary."
        try: return f'opened {host.add_root(path)}. Open folders: ' + ', '.join(host.roots)
        except Exception as e: return err(f'could not open {path}', e)

    @summary(lambda a: f'View {a.get("path","")}' + (f':{a.get("start","")}-{a.get("end","")}' if a.get('start') or a.get('end') else ''))
    def view_file(path: str, start: int = 0, end: int = 0) -> str:
        "Read `path` as `lineno|hash|content` lines; `start`/`end` bound the range."
        p, refused = resolved(host, path, reading=True)
        if refused: return refused
        try: text = host.read(str(p))
        except Exception: text = None
        if text is None and not p.exists(): return err(f'no such file: {p}')
        view = str(lnhashview(text, start or None, end or None) if text is not None else lnhashview_file(str(p), start or None, end or None))
        return clip_lines(view.splitlines(), start=(start or 1), n=mx,
                          more='call view_file(path, start={next}) to continue')

    @writes
    @summary(lambda a: f'Edit {a.get("path","")}')
    def replace_text(path: str, edits: list[dict],  # [{"oldText": "exact text", "newText": "replacement"}, ...]
                     ) -> str:
        "Replace exact text in a file: each `{oldText, newText}` must match once; all apply or none; returns the diff."
        p, refused = resolved(host, path, writing=True)
        if refused: return refused
        after, before, n, refused = _replace(lambda: host.read(str(p)), edits, str(p))
        if refused: return refused
        try: host.write(str(p), after)
        except Exception as e: return err('write failed', e)
        return clip(f'replaced {n} block(s) in {p}\n' + diff_text(before, after, str(p)), mx)

    @writes
    @summary(lambda a: f'Create {a.get("path","")}')
    def create_file(path: str, text: str = '') -> str:
        "Create or overwrite a whole file; change an existing one with `replace_text`."
        p, refused = resolved(host, path, writing=True)
        if refused: return refused
        try: return f'wrote {host.write(str(p), text)}'
        except Exception as e: return err('write failed', e)

    if host is not None and not host.writes: return [view_file]
    return [view_file, replace_text, create_file, add_root]

# %% ../nbs/02_tools.ipynb #16ef86e9
def exhash_tools(host, mx=MAX_TOOL_CHARS):
    "The hash-addressed editor, offered only where a caller asks for it (`optin=('exhash',)`)."

    @writes
    @summary(lambda a: f'Edit {a.get("path","")}')
    def edit_file(path: str, commands: list[list]) -> str:
        "Apply exhash commands addressed by the `lineno|hash|` prefixes `view_file` shows; writes only if every command succeeds."
        p, refused = resolved(host, path, writing=True)
        if refused: return refused
        try: cs = cmds(commands)
        except Exception as e: return err('could not parse commands', e)
        if not cs: return err('no commands given')
        try: return clip(str(file_exhash(str(p), *cs)), mx)
        except Exception as e: return err('edit failed', e)

    if host is not None and not host.writes: return []
    return [edit_file]

# %% ../nbs/02_tools.ipynb #3c171dfb
def notebook_tools(host, mx=MAX_TOOL_CHARS):
    "Notebooks, addressed by cell id rather than by line."

    @summary(lambda a: f'Cells of {a.get("path","")}')
    def notebook_cells(path: str) -> str:
        "List a notebook's cells as `id  type  first line`; the ids are what `view_cell` and `edit_cell` address."
        rows = attempt('could not read notebook', lambda: host.nb_cells(str(readable(host, path))))
        if isinstance(rows, str): return rows
        return clip('\n'.join(f'{i}  {t:8} {(s or "").strip().splitlines()[0][:100] if (s or "").strip() else ""}' for i, t, s in rows) or '(empty notebook)', mx)

    @summary(lambda a: f'View {a.get("path","")} cell {a.get("cell_id","?")}')
    def view_cell(path: str, cell_id: str) -> str:
        "One notebook cell's source, numbered; copy `oldText` for `edit_cell` from here."
        try: _, _, src = host.nb_cell(str(readable(host, path, must_exist=True)), cell_id)
        except Exception as e: return err('could not read cell', e)
        return clip_lines([f'{i}: {l}' for i, l in enumerate(src.splitlines() or [''], 1)], n=mx)

    @writes
    @summary(lambda a: f'Edit {a.get("path","")} cell {a.get("cell_id","?")}')
    def edit_cell(path: str, cell_id: str, edits: list[dict],  # [{"oldText": "exact text", "newText": "replacement"}, ...]
                  ) -> str:
        "Replace exact text in one cell: each `{oldText, newText}` must match once; all apply or none; returns the diff."
        p, refused = resolved(host, path, writing=True)
        if refused: return refused
        after, before, n, refused = _replace(lambda: host.nb_cell(str(p), cell_id)[2], edits, f'{p}#{cell_id}')
        if refused: return refused
        try: cid = host.nb_set_cell(str(p), cell_id, after)
        except Exception as e: return err('could not write cell', e)
        return clip(f'replaced {n} block(s) in cell {cid} of {p}\n' + diff_text(before, after, f'{p}#{cid}'), mx)

    @writes
    @summary(lambda a: f'Add {a.get("cell_type","code")} cell to {a.get("path","")}')
    def add_cell(path: str, source: str, index: int = -1, cell_type: str = 'code') -> str:
        "Insert a new cell into a notebook at `index` (-1 appends); creates the notebook if needed."
        p, refused = resolved(host, path, writing=True)
        if refused: return refused
        said = attempt('could not add cell', lambda: host.nb_add_cell(str(p), source, int(index), cell_type))
        return said if failed(said) else f'added cell {said} to {path}'

    return [notebook_cells, view_cell, edit_cell, add_cell]

# %% ../nbs/02_tools.ipynb #68bb2099
def web_tools(host, mx=MAX_TOOL_CHARS):
    "The web, for the questions whose answer depends on current documentation."

    @summary(lambda a: f'Web search: {_1(a.get("query"))}')
    def web_search(query: str) -> str:
        "Search the web and return titles and URLs."
        docs = host.web_search(query, n=MAX_HITS)
        if not docs: return f'no results ({host.research_note})'
        return clip('\n'.join(f'{d.title}\n  {d.url}' for d in docs))

    @summary(lambda a: f'Web fetch: {_1(a.get("url"), 120)}')
    def read_url(url: str, remember: bool = True) -> str:
        "Read `url` as text suited to its kind (article, PDF, repo file, transcript); the page enters durable memory unless `remember=False`."
        d = host.read_url(url, remember=remember)
        return clip(d.text if d else f'could not read {url} ({host.research_note})')

    def no_save_read(url: str) -> str:
        "Read one web page without saving it to durable memory."
        return read_url(url, False)
    no_save_read.__name__ = 'read_url'
    read_url.read_only = no_save_read

    return [web_search, read_url]

# %% ../nbs/02_tools.ipynb #0acd5a7f
def research_tools(host, mx=MAX_TOOL_CHARS):
    "The slow web tool, offered where a caller asks for it (`optin=('research',)`)."

    @acts
    @summary(lambda a: f'Research: {_1(a.get("query"))}')
    def research(query: str) -> str:
        "Search the web and read the top results into one cited digest; slower than `web_search`, for what one page will not settle."
        return clip(host.research(query) or f'nothing found ({host.research_note})', mx)

    if host is not None and hasattr(host, 'can') and not host.can('web'): return []
    return [research]

# %% ../nbs/02_tools.ipynb #13dd6936
def memory_tools(host, mx=MAX_TOOL_CHARS):
    "Durable pages and research recalled as document sections rather than flat snippets."

    @summary(lambda a: f'Memory search: {_1(a.get("query"))}')
    def memory_search(query: str, limit: int = 8) -> str:
        "Search remembered pages and return matching sections with breadcrumbs, each with its `age` in seconds and whether it is `stale`."
        rows = attempt('memory search failed', lambda: list(host.memory_search(query, int(limit))))
        return rows if isinstance(rows, str) else clip(json.dumps(rows, default=str), MAX_TOOL_CHARS * 2)

    @summary(lambda a: f'Memory read {a.get("ref") or "(roots)"}')
    def memory_read(ref: str = '') -> str:
        "Browse or read memory: empty lists every document, a document id or title shows its headings, a node id (`doc#n`) returns the section text."
        ref = str(ref or '').strip()
        f = (lambda: host.memory_read(ref)) if '#' in ref else (lambda: host.memory_tree(ref))
        got = attempt('memory read failed', f)
        return got if isinstance(got, str) else clip(json.dumps(got, default=str), MAX_TOOL_CHARS * 3)

    @summary(lambda a: f'Remember {_1(a.get("title") or a.get("text"))}')
    def remember(text: str, title: str = '', tags: str = '', key: str = '') -> str:
        "Store a conclusion in durable memory; `tags` is comma-separated; the same `key` later replaces this note instead of adding one."
        kw = {'key': key} if key else {}
        d = attempt('could not remember', lambda: host.remember(text, title=title or None, tags=[t.strip() for t in tags.split(',') if t.strip()], **kw))
        return d if isinstance(d, str) else f"remembered {d.get('title')!r} as {d.get('doc_id')}" + (' (replaced)' if d.get('replaced') else '')

    @writes
    @summary(lambda a: f'Forget {a.get("doc_id","?")}')
    def memory_forget(doc_id: str) -> str:
        "Delete a remembered document and its index data; only at the user's request."
        ok = attempt('memory purge failed', lambda: host.memory_forget(doc_id))
        return ok if failed(ok) else ('forgot document' if ok else 'document was not forgotten')

    return [memory_search, memory_read, remember, memory_forget]

# %% ../nbs/02_tools.ipynb #e919c44b
KINDS = {'url': 'url', 'remind': 'remind', 'search': 'web', 'folder': 'folder'}   #: the model's kind -> the vault's action

def watch_tools(host, mx=MAX_TOOL_CHARS):
    "Standing interests: what to put back on the desk later, and what has come due now."

    @acts
    @summary(lambda a: f'Watch {a.get("kind","url")} {_1(a.get("target"), 80)} every {a.get("every","1d")}')
    def watch(target: str, kind: str = 'url', every: str = '1d', note: str = '', instructions: str = '', pattern: str = '') -> str:
        "Keep re-reading `target` every `every`: kind `url` (a page), `remind` (text filed on schedule), `search` (a web query), `folder` (a path; needs `instructions`, `pattern` narrows)."
        if kind not in KINDS: return err('watch', ValueError(f'kind must be one of {", ".join(KINDS)}'))
        ok = getattr(host, 'watch_actions', None) or ('remind',)
        if KINDS[kind] not in ok: return err('watch', ValueError(f'this host only watches {", ".join(k for k, a in KINDS.items() if a in ok)}'))
        if kind == 'folder' and not str(instructions).strip(): return err('watch', ValueError('a folder watch needs `instructions`: the brief its reviewer gets'))
        kw = {k: v for k, v in dict(instructions=instructions, pattern=pattern).items() if v}
        w = attempt('could not watch', lambda: host.watch(target, action=KINDS[kind], every=every, note=note or None, **kw))
        return w if isinstance(w, str) else f"watching {kind} {target} as {w['id']}, every {every}"

    @summary(lambda a: 'List watches' + (' (due)' if a.get('due_only') else ''))
    def list_watches(due_only: bool = False) -> str:
        "Every watch and reminder, soonest first, as `id  kind  every  runs  last status  target`; `due_only` keeps what has come due."
        ws = attempt('could not list watches', lambda: host.watches(due_only=bool(due_only)))
        if isinstance(ws, str): return ws
        if not ws: return 'nothing is being watched'
        return clip('\n'.join(f"{w['id']}  {(w.get('kind') or w['action']):8} every {int(w['every'])}s  runs={w['runs']}"
                              f"  {w.get('last_status') or 'never run'}  {str(w['target'])[:80]}" for w in ws), mx)

    @writes
    @summary(lambda a: f'Cancel watch {a.get("watch_id","?")}')
    def cancel_watch(watch_id: str) -> str:
        "Delete a watch by id at the user's request."
        said = attempt('could not cancel', lambda: host.unwatch(watch_id))
        return said if failed(said) else f'cancelled {watch_id}'

    return [watch, list_watches, cancel_watch]

# %% ../nbs/02_tools.ipynb #27b30123
def ask_tools(host, mx=MAX_TOOL_CHARS):
    "Model-backed answers from memory."

    @summary(lambda a: f'Ask memory: {_1(a.get("question"))}')
    def ask_memory(question: str, document: str = '', instruction: str = '') -> str:
        "Answer a question from remembered research, with citations; `document` limits the source; private sources withhold identifying details, so `instruction` asks for a count, total, comparison or yes/no instead."
        r = attempt('could not ask memory', lambda: host.ask(question, ref=document or None, instruction=instruction))
        if isinstance(r, str): return r
        rows = [str(r.get('answer') or '(no answer)')]
        if (p := r.get('pii')) and p.get('has_pii'):
            rows.append(f"\n[policy {r.get('policy', 'local')}: withheld {', '.join(sorted(p.get('identifying') or {}))}; ask with `instruction=` for a count, total, comparison or yes/no]")
        if (c := r.get('cited')):
            rows.append('\n' + '\n'.join(f"[{x['n']}] {x['breadcrumb']}  ({x['node_id']})" for x in c))
        return clip('\n'.join(rows), MAX_TOOL_CHARS * 2)

    return [ask_memory]

# %% ../nbs/02_tools.ipynb #5632a9ae
def session_tools(host, mx=MAX_TOOL_CHARS):
    "The live kernel the user is working in, and the terminal they are looking at."

    @writes
    @summary(lambda a: f'Run python: {_1((a.get("code") or "").strip().splitlines()[0] if a.get("code") else "")}')
    def run_python(code: str) -> str:
        "Run Python in the user's live namespace; bind results to new names, since rebinding or deleting the user's variables is refused."
        return clip(attempt('run failed', lambda: host.run_python(code)))

    @acts
    @summary(lambda a: f'Inspect: {_1((a.get("code") or "").strip().splitlines()[0] if a.get("code") else "")}' + ('' if (a.get('scope') or 'isolated') == 'isolated' else f'  [{a["scope"]}]'))
    def inspect_python(code: str = '', scope: str = 'isolated') -> str:
        "Look at live variables without changing them; empty `code` lists them; `scope` is `isolated` (sandboxed copy) or `overlay` (real interpreter, private layer)."
        if not str(code or '').strip(): return clip(host.list_vars() or '(empty session)')
        return clip(attempt('inspection failed', lambda: host.inspect_python(code, scope=scope)))

    @summary(lambda a: 'Read terminal')
    def read_terminal(lines: int = 200) -> str:
        "Read recent IDE terminal output without running a command."
        return clip(host.terminal_text(int(lines)) or 'the terminal has printed nothing yet')

    return [run_python, inspect_python, read_terminal]

# %% ../nbs/02_tools.ipynb #0eb6a349
def shell_tools(host, mx=MAX_TOOL_CHARS):
    "Shell command tools."

    @writes
    @summary(lambda a: f'Run {_1(a.get("command"), 110)}')
    def run_shell(command: str, cwd: str = '', timeout: int = 120) -> str:
        "Run one terminating command (`cwd` inside the open folders, killed after `timeout` s) and return exit code and output; servers go to `run_shell_bg`."
        cmd = str(command or '').strip()
        if not cmd: return err('no command given')
        try: code, out = host.run_cmd(cmd, cwd=(str(cwd).strip() or None), timeout=int(timeout))
        except NotImplementedError: raise
        except Exception as e: return err('command could not be run', e)
        head = f'exit {code}' + ('' if code == 0 else '  (command FAILED)')
        body = clip((out or '').rstrip() or '(no output)', max(500, mx - 200),
                    more='re-run narrowing the command (a single test, `| tail -50`) rather than repeating it')
        return f'{head}\n{body}' if code == 0 else f'{ERR}{head}\n{body}'

    @writes
    @summary(lambda a: f'Run in background {_1(a.get("command"), 100)}')
    def run_shell_bg(command: str, cwd: str = '') -> str:
        "Start a command that keeps running and return its id; read it with `shell_output`, end it with `shell_stop`."
        cmd = str(command or '').strip()
        if not cmd: return err('no command given')
        rid = attempt('command could not be started', lambda: host.run_cmd_bg(cmd, cwd=(str(cwd).strip() or None)))
        return rid if failed(rid) else f'started {rid}; read it with shell_output({rid!r})'

    @summary(lambda a: f'Read {a.get("run_id", "?")}')
    def shell_output(run_id: str, tail: int = 200) -> str:
        "A background command's state and its last `tail` lines."
        got = attempt('no such command', lambda: host.cmd_output(run_id, int(tail)))
        if isinstance(got, str): return got
        state, text = got
        return clip(f'{state}\n{text or "(no output yet)"}', mx)

    @acts
    @summary(lambda a: f'Stop {a.get("run_id", "?")}')
    def shell_stop(run_id: str) -> str:
        "Stop a background command."
        return attempt('could not stop', lambda: host.cmd_stop(run_id))

    return [run_shell, run_shell_bg, shell_output, shell_stop]

# %% ../nbs/02_tools.ipynb #80208a7b
def api_tools(host, mx=MAX_TOOL_CHARS):
    "Read an API specification, browse what it declares, and call one operation."

    @summary(lambda a: f'Load API spec {_1(a.get("src"), 80)}')
    def api_load(src: str, name: str = '') -> str:
        "Load an OpenAPI or discovery document and return its operation count and groups."
        try: return clip(json.dumps(host.api_load(src, name), default=str), mx)
        except Exception as e: return err('could not load the spec', e)

    @summary(lambda a: 'API operations' + (f' in {a["group"]}' if a.get('group') else '') + (f' matching {_1(a["match"], 40)}' if a.get('match') else ''))
    def api_ops(group: str = '', name: str = '', match: str = '', offset: int = 0) -> str:
        """List loaded API operations and signatures.
        Filter with `group` or `match`. Use `offset` for later pages.
        """
        try:
            rows = host.api_ops(group, name, match, offset=offset)
            total = host.api_count(group=group, name=name, match=match)
            out = {'operations': rows}
            if offset or len(rows) < total:
                out |= {'matched': total, 'showing': f'{offset + 1}-{offset + len(rows)}',
                        'more': f'call again with offset={offset + len(rows)}'} if offset + len(rows) < total else {'matched': total}
            return clip(json.dumps(out, default=str), mx)
        except Exception as e: return err('could not read the operations', e)

    @acts
    @summary(lambda a: f'API call {a.get("operation","?")}')
    def api_call(operation: str, name: str = '', params: dict = None) -> str:
        "Call `operation` with the declared `params`. Undeclared parameters are errors."
        try: return clip(json.dumps(host.api_call(operation, name, **(params or {})), default=str), mx)
        except Exception as e: return err(f'{operation} failed', e)

    return [api_load, api_ops, api_call]

# %% ../nbs/02_tools.ipynb #6ae4e312
def skill_tools(host, get_skills, mx=MAX_TOOL_CHARS):
    "Reading the skills the system prompt lists."

    @summary(lambda a: f'Read skill {a.get("name","?")}')
    def read_skill(name: str) -> str:
        "Read a discovered skill in full before doing the work it covers."
        ss = get_skills()
        s = find(ss, name)
        if s is None:
            return f'no skill matching {name!r}. Available: ' + ', '.join(x.name for x in ss)
        body = f'<skill name="{s.name}" from="{s.where}">\n{s.text()}\n</skill>'
        return clip(body, max(MAX_TOOL_CHARS * 3, len(body)))   # `Skill.text` already held the budget

    return [read_skill]

# %% ../nbs/02_tools.ipynb #dab555b1
def author_tools(host, mx=MAX_TOOL_CHARS):
    "Writing a project skill, offered where a caller asks for it (`optin=('author',)`)."

    @writes
    @summary(lambda a: f'Create skill {a.get("name","?")}')
    def create_skill(name: str, description: str, instructions: str) -> str:
        "Create `.agents/skills/NAME/SKILL.md` (kebab-case `name`; `description` says when it applies; `instructions` is its Markdown body) without overwriting one; `/reload` advertises it."
        name = str(name or '').strip()
        if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', name):
            return 'skill name must be lowercase kebab-case (for example, notebook-tests)'
        if not str(description or '').strip(): return 'skill description is required'
        if not str(instructions or '').strip(): return 'skill instructions are required'
        roots = list(host.roots or ())
        if not roots: return 'open a project folder before creating a skill'
        target = Path(host.check(Path(roots[0])/'.agents'/'skills'/name/'SKILL.md'))
        exists = target.exists()
        if not exists:
            try: exists = host.read(str(target)) is not None
            except Exception: pass
        if exists: return f'refusing to overwrite existing skill: {target}'
        title = json.dumps(name, ensure_ascii=False)
        desc = json.dumps(' '.join(str(description).split()), ensure_ascii=False)
        text = f'---\nname: {title}\ndescription: {desc}\n---\n\n{str(instructions).strip()}\n'
        try: host.write(str(target), text)
        except Exception as e: return err('could not create skill', e)
        return f'created {target}; run /reload to load it into the current agent'

    if host is not None and not host.writes: return []
    return [create_skill]

# %% ../nbs/02_tools.ipynb #8e7cc301
RESPONSES_API = 'https://api.openai.com/v1/responses'
IMAGE_API = 'https://api.openai.com/v1/images/generations'
IMAGE_MODEL = 'gpt-image-1'
IMAGE_SIZES = ('1024x1024', '1536x1024', '1024x1536', 'auto')
API_VENDORS = ('openai/', 'azure/')

# %% ../nbs/02_tools.ipynb #14d82ec8
def media_dir(session=''):
    "Return the session's media directory."
    d = Path(session or '.') / 'media'
    d.mkdir(parents=True, exist_ok=True)
    return d

def mime_for(path):
    "Detect a file's MIME type from bytes, then its suffix."
    try: m = detect_mime(Path(path).read_bytes()[:64])
    except OSError: m = None
    return m or mimetypes.guess_type(str(path))[0] or 'image/png'

def save_media(m, session='', stem='image'):
    "Save one media item under the session and return its path."
    mime = m.get('mime') or 'image/png'
    ext = mimetypes.guess_extension(mime) or '.' + mime.split('/')[-1]
    d = media_dir(session)
    seen = [int(g.group(1)) for p in d.glob(f'{stem}-*')
            if (g := re.match(rf'{re.escape(stem)}-(\d+)$', p.stem))]
    n = 1 + max(seen, default=0)   # the highest used, not the count, so a delete frees no name
    p = d / f'{stem}-{n}{ext}'
    p.write_bytes(m['data'])
    return p

def image_available(): return bool(os.environ.get('OPENAI_API_KEY'))

def _hdrs(): return {'Authorization': f"Bearer {os.environ['OPENAI_API_KEY']}"}

def _post_image(prompt, size, n, timeout=120, model=IMAGE_MODEL):
    "Raw `data` rows from the images endpoint."
    import httpx
    r = httpx.post(IMAGE_API, timeout=timeout, headers=_hdrs(), json={'model': model, 'prompt': prompt, 'size': size, 'n': n})
    r.raise_for_status()
    return r.json().get('data') or []

def api_model(model):
    "Strip a supported API-vendor prefix from a model id."
    s = str(model or '')
    for v in API_VENDORS:
        if s.startswith(v): return s[len(v):]
    return s

def _post_responses(prompt, model, timeout=300):
    "Return a Responses API image-generation reply."
    import httpx
    r = httpx.post(RESPONSES_API, timeout=timeout, headers=_hdrs(),
                   json={'model': api_model(model), 'input': prompt, 'tools': [{'type': 'image_generation'}]})
    r.raise_for_status()
    return r.json()

# %% ../nbs/02_tools.ipynb #7a99e2b6
def image_tools(host, mx=MAX_TOOL_CHARS, session='', draws_itself=None, from_reply=None, model_id='',
                on_media=None):
    "Drawing: by the turn's own model where it can, and by the images endpoint where it cannot."

    @acts
    @summary(lambda a: f'Draw: {_1(a.get("prompt"), 100)}')
    def generate_image(prompt: str, size: str = '1024x1024', n: int = 1, model: str = '') -> str:
        """Generate and save images.
        `size` is 1024x1024, 1536x1024, 1024x1536, or auto. A non-empty `model` uses the images endpoint.
        """
        if not image_available(): return err('image generation is unavailable', 'OPENAI_API_KEY is not set')
        if size not in IMAGE_SIZES: return err('unknown size', f'{size!r}; use one of {", ".join(IMAGE_SIZES)}')
        mid = model_id() if callable(model_id) else model_id   # the turn's model, not the one it was built with
        own = bool(draws_itself and draws_itself() and from_reply and mid)
        try:
            if not model and own: media = from_reply(_post_responses(prompt, mid))
            else: media = [{'mime': 'image/png', 'data': b64decode(r['b64_json'])}
                for r in _post_image(prompt, size, max(1, min(int(n or 1), 4)), model=api_model(model or IMAGE_MODEL)) if r.get('b64_json')]
        except Exception as e: return err('could not generate the image', e)
        if not media: return err('the model returned no image', 'the reply carried no picture')
        try: out = [save_media(m, session, 'generated') for m in media]
        except Exception as e: return err('could not save the image', e)
        if on_media: on_media(out)
        return clip('\n'.join(str(p) for p in out))

    return [generate_image]

# %% ../nbs/02_tools.ipynb #49342acf
from gheasy.repo import GitRepo, STATE_KEYS, REMOTE_OPS

# %% ../nbs/02_tools.ipynb #5c1e1c29
def _report(r, out=None):
    "A git write's report: what gheasy said, its undo token when it journaled one, and the repository state."
    d = out if isinstance(out, dict) else {}
    said = (d.get('summary') or d.get('message') or '') if d else str(out or '').strip()
    return ({'result': said, 'summary': d.get('summary', said), 'undo': d.get('undo', ''), 'undoes': d.get('undoes', ''),
             'head': d.get('head', ''), 'moved': bool(d.get('moved', False))} | {k: r.info()[k] for k in STATE_KEYS})

def git_tools(host, mx=MAX_TOOL_CHARS):
    "Git bound to one open repository, kept inside the host's roots; writes report an undo token."
    os.environ.setdefault('GIT_TERMINAL_PROMPT', '0')
    def repo(path=''):
        roots = L(host.roots).map(lambda r: Path(r).expanduser().resolve())
        if not roots: raise ValueError('open a project folder first')
        found = GitRepo.at(host.check(path or getattr(host, 'project', '') or roots[0], must_exist=True))
        if not any(found.root.is_relative_to(r) for r in roots):
            raise ValueError(f'Git root {found.root} is outside the open folders; open the repository root first')
        return found
    def answer(what, path, make, text=False):
        try:
            r = make(repo(path))
            return clip(r if text else json.dumps(r, indent=2), mx * 2)
        except Exception as e: return err(what, e)
    @summary(lambda a: 'Git status')
    def git_status(path: str = '') -> str:
        "Branch, upstream, ahead/behind counts, local and remote branches, and every changed file."
        return answer('git status', path, _report)
    @summary(lambda a: f'Git divergence vs {a.get("against") or "upstream"}')
    def git_divergence(against: str = '', path: str = '') -> str:
        "How this branch differs from `against` (default its upstream), with fast-forward, merge, rebase and reset rehearsed: conflicts, where a rebase would stop, and a recommendation."
        return answer('git divergence', path, lambda r: r.divergence(against))
    @summary(lambda a: 'Git diff' + (' (staged)' if a.get('staged') else ''))
    def git_diff(staged: bool = False, path: str = '') -> str:
        "Unified diff of the working tree, or of the index with `staged`; `path` narrows to a file or folder."
        return answer('git diff', path, lambda r: r.diff(path=str(host.check(path)) if path else '', staged=staged) or '(no changes)', text=True)
    @summary(lambda a: f'Git log {a.get("n", 10)}')
    def git_log(n: int = 10, path: str = '') -> str:
        "The last `n` commits: short id, author, subject."
        return answer('git log', path, lambda r: [{k: c[k] for k in ('short', 'author', 'subject')} for c in r.history(limit=int(n), ref='HEAD')])
    @writes
    @summary(lambda a: f'Git {"amend" if a.get("amend") else "commit"}: {_1(a.get("message"), 80)}')
    def git_commit(message: str, paths: str = '', amend: bool = False) -> str:
        "Commit what is staged (or stage `paths`, space-separated, first) with `message`; `amend` folds it into the last commit; returns an `undo` token."
        def go(r):
            if (ps := shlex.split(paths or '')): r.stage(ps)
            return _report(r, r.commit(str(message), amend=amend))
        return answer('git commit', '', go)
    @writes
    @summary(lambda a: f'Git {"create" if a.get("create") else "checkout"} {a.get("branch","?")}')
    def git_checkout(branch: str, create: bool = False, path: str = '') -> str:
        "Switch to `branch` (a `REMOTE/BRANCH` makes a tracking branch); `create` makes a new branch from HEAD; uncommitted work is carried or refused, never lost."
        b = str(branch or '').strip()
        def go(r):
            if create: r.create(b); return _report(r, f'created and switched to {b}')
            return _report(r, r.checkout(b))
        return answer('git checkout', path, go)
    @writes
    @summary(lambda a: f'Git stash {a.get("action", "push")}')
    def git_stash(action: str = 'push', message: str = '', path: str = '') -> str:
        "`push` sets the working changes aside (with `message`); `pop`, `apply` or `drop` acts on the latest stash."
        ops = {'push': lambda r: r.stash(str(message or '')), 'pop': lambda r: r.stash_pop(),
               'apply': lambda r: r.stash_apply(), 'drop': lambda r: r.stash_drop()}
        if action not in ops: return err('git stash', ValueError(f'action must be one of {", ".join(ops)}'))
        return answer(f'git stash {action}', path, lambda r: _report(r, ops[action](r)))
    @writes
    @summary(lambda a: f'Git {a.get("op","fetch")}' + (' (publish)' if a.get('publish') else ''))
    def git_remote(op: str = 'fetch', publish: bool = False, path: str = '') -> str:
        "`fetch` all remotes, `pull` fast-forward only (autostash), or `push`; `publish` sets the upstream for a branch pushed the first time."
        if op not in REMOTE_OPS: return err('git remote', ValueError(f'op must be one of {", ".join(REMOTE_OPS)}'))
        go = (lambda r: r.push(publish=publish)) if op == 'push' else (lambda r: getattr(r, op)())
        return answer(f'git {op}', path, lambda r: _report(r, go(r)))
    return [git_status, git_divergence, git_diff, git_log, git_commit, git_checkout, git_stash, git_remote]

# %% ../nbs/02_tools.ipynb #8cc4fdac
#: the Capability class -> the factory that builds its group. The group name lives only on
#: `cls.group`; order is the order a model sees the tools in. `Host` carries group='file'.
GROUPS = ((CodeHost, code_tools), (Host, file_tools), (NotebookHost, notebook_tools),
          (WebHost, web_tools), (MemoryHost, memory_tools), (AskHost, ask_tools),
          (WatchHost, watch_tools),
          (ApiHost, api_tools), (SessionHost, session_tools), (ShellHost, shell_tools),
          (GitHost, git_tools))

def tools_for(host, get_skills=None, extra=(), mx=MAX_TOOL_CHARS, drop=(), image=None):
    """Every tool this host declares it can support, plus whatever else was registered.

    `image` is a built image group, or None. It needs to know what the turn's model can do, and a
    host does not, so the frontend that knows builds it and passes it in.
    """
    drop = set(drop or ())
    tools = [t for cap, f in GROUPS if cap.group not in drop and host.can(cap.group) for t in f(host, mx)]
    if get_skills is not None and 'skill' not in drop: tools += skill_tools(host, get_skills, mx)
    if image is not None and 'image' not in drop: tools += list(image)
    return tools + list(extra or ())

# %% ../nbs/02_tools.ipynb #d6587fa0
@functools.cache
def tool_groups():
    "Every tool name shalya can build, mapped to the group that owns it. `image` and `skill` included."
    out = {}
    for cap, factory in GROUPS:
        for t in factory(None): out[t.__name__] = cap.group
    for t in image_tools(None): out[t.__name__] = 'image'
    for t in skill_tools(None, lambda: ()): out[t.__name__] = 'skill'
    return out

def group_of(name, default=''):
    "Which group a tool belongs to, or `default` for a name shalya does not build."
    return tool_groups().get(str(name), default)

tool_groups()   # build once at import so `summarise` can label a bare name

# %% ../nbs/02_tools.ipynb #01e94cbe
def _writing(t): return is_write(t) or getattr(t, '__name__', '') in WRITE_TOOLS
def _acting(t):  return has_effect(t) or getattr(t, '__name__', '') in ACTING_TOOLS

def read_only(tools, max_calls=None, writes=False, effects=True, block=()):
    "The tools an agent may have when it must not act, optionally behind a hard call budget."
    blocked = set(block or ())
    allowed = []
    for t in tools:
        if getattr(t, '__name__', '') in blocked: continue
        if not effects and _acting(t): continue
        if writes: allowed.append(t)
        elif (safe := getattr(t, 'read_only', None)) is not None: allowed.append(safe)
        elif not _writing(t): allowed.append(t)
    if max_calls is None: return allowed
    state, lock = {'n': 0}, threading.Lock()

    def guarded(f):
        @functools.wraps(f)
        def call(*args, **kw):
            with lock:
                state['n'] += 1
                over = state['n'] > max_calls
            if over:
                return ('Tool budget exhausted. Stop calling tools and return the '
                        'best evidence-backed answer now.')
            return f(*args, **kw)
        return call
    return [guarded(t) for t in allowed]
